-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\eduyilmet001\Desktop\simulink_vhdlcoder\CLKDIV_LED_basic\clkdiv6hz.vhd
-- Created: 2023-10-05 12:09:47
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: clkdiv6hz
-- Source Path: CLKDIV_LED_basic/clkdiv6hz
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY clkdiv6hz IS
  PORT( CLK100MHZ                         :   IN    std_logic;
        RESETN                            :   IN    std_logic;
        CLK6HZ                            :   OUT   std_logic
        );
END clkdiv6hz;


ARCHITECTURE rtl OF clkdiv6hz IS

  -- Signals
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL Add2_out1                        : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Unit_Delay1_out1                 : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Add2_add_cast                    : unsigned(23 DOWNTO 0);  -- ufix24
  SIGNAL Extract_Bits5_out1               : std_logic;  -- ufix1_E23
  SIGNAL Cast_To_Boolean_out1             : std_logic;

BEGIN
  -- With each CLK cycle '1' is added to the output
  -- input signal is latched (delayed) by a 100MHz CLK cycle (10ns)
  -- MSB is the 6Hz CLK (100MHz/(2^N))
  -- Type cast to boolean (single bit)
  -- Single bit 6 Hz CLK

  Constant_out1 <= '1';

  Unit_Delay1_process : PROCESS (CLK100MHZ, RESETN)
  BEGIN
    IF RESETN = '0' THEN
      Unit_Delay1_out1 <= to_unsigned(16#000000#, 24);
    ELSIF CLK100MHZ'EVENT AND CLK100MHZ = '1' THEN
      Unit_Delay1_out1 <= Add2_out1;
    END IF;
  END PROCESS Unit_Delay1_process;


  Add2_add_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Constant_out1;
  Add2_out1 <= Add2_add_cast + Unit_Delay1_out1;

  Extract_Bits5_out1 <= Add2_out1(23);

  
  Cast_To_Boolean_out1 <= '1' WHEN Extract_Bits5_out1 /= '0' ELSE
      '0';

  CLK6HZ <= Cast_To_Boolean_out1;

END rtl;

